### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mineschan** [YangJing96/SlideMenuLayout#1]
Thanks for the good work. I'm using SlideMenuLayout in my new project. May I request some features to be added if possible?

1) Option to click on content view to close menu when it's opening
2) Option to dim the content view automatically
3) Option to toggle the parallax effect

**Comment by JingYeoh** [comment]
Thanks for your suggest, i will do that on the weekend. and i will let you know if the feature is done.(:

**Comment by mineschan** [comment]
Thank you that's sweet ;)

**Comment by JingYeoh** [comment]
the features is done,please use version 1.2.0,if you find any error,please let me know. :)

**Comment by mineschan** [comment]
Thank you so much ;)

**Comment by mineschan** [comment]
Updated and tested, they work perfectly!
