### ISSUE TITLE
demo x轴超过屏幕1/2 无法向左滑动

### ISSUE THREAD

**Issue by LostDeer** [YangJing96/SlideMenuLayout#10]
X轴超过 超过屏幕1/2  ContentView 被onInterceptTouchEvent 拦截  无法滑动

**Comment by JingYeoh** [comment]
@LostDeer 修改过demo中的参数吗？demo运行是没有问题的.

**Comment by LostDeer** [comment]
刚才重新下了遍demo
手指放在超过屏幕宽度的2/3处，向左滑动，无法滑动

**Comment by JingYeoh** [comment]
@LostDeer 这是为了在主体含有滑动事件做的特殊处理，请提供不支持的实际场景，谢谢～
