### ISSUE TITLE
点击主体布局无法关闭侧滑菜单

### ISSUE THREAD

**Issue by wuconghui** [YangJing96/SlideMenuLayout#3]
设置slidePadding之后，侧滑菜单打开时候点击主体布局无法关闭侧滑菜单

**Comment by JingYeoh** [comment]
@wuconghui 默认点击主体菜单是不关闭侧滑菜单的，请在布局中设置`contentToggle`属性的值为`true`，或者在Java代码中设置`setContentToggle(true)`

**Comment by wuconghui** [comment]
已经可以了，但是现在如果点击到了主体菜单的控件，也会响应点击事件，如何只关闭侧滑菜单而不让主体菜单的控件响应呢，不知您是否有什么办法解决这一问题

**Comment by JingYeoh** [comment]
@wuconghui 已经修复，请使用`v1.2.1`版本.

**Comment by wuconghui** [comment]
感谢
