### ISSUE TITLE
Adding WebView

### ISSUE THREAD

**Issue by EhsanMomeni81** [YangJing96/SlideMenuLayout#4]
Hi,

Just a quick question. I'm new to Android programming and still learning my copy & paste metod.

Is it possible to add WebView to the slide out menu? 
I would like to have items (teams) the left slide menu and when you click on one of the items (teams) it will open a webview?

Thanks

**Comment by JingYeoh** [comment]
@EhsanMomeni81  `WebView` is a `View` , `SlideMenuLayout` can let any `View` as slide menu.
you should handle your own code according to your business if you wanna open a `WebView`.
