### ISSUE TITLE
怎么禁止滑动显示菜档

### ISSUE THREAD

**Issue by rmtic** [YangJing96/SlideMenuLayout#5]
我有一个横向的滚动，做滑动后会跟他有冲突，怎么取消控件左滑动出菜单

**Comment by JingYeoh** [comment]
@rmtic 在布局中设置`slideMode`属性，支持`left/right/both/none`四个值，你可以选择自己想要打开/关闭的侧滑菜单。
或者你可以通过`setSlideMode()`方法来进行设置。

>如果有滑动冲突的场景，请详细描述滑动场景，我来修复。

**Comment by rmtic** [comment]
可以了！谢谢你，大神你的控件对我太有帮助了！

**Comment by rmtic** [comment]
但是,我改成none后，滑动开菜单，在滑动回去，会卡在屏幕，菜单没办法完全缩回去

**Comment by JingYeoh** [comment]
@rmtic Thanks for your issue.是我这边的错误，对`none`状态下没有进行完全拦截，我会尽快修复。

**Comment by rmtic** [comment]
最快要多久，我打算用你写的框架。要是能添加个禁止内容区滑动的方法就更好了！

**Comment by JingYeoh** [comment]
@rmtic 白天有点事情，晚上回去就可以完成修复，此时的滑动方案是为了解决各种场景下的滑动冲突，如需要新的特性，请另起一个`issue`，不过近期有点忙，估计不会很快添加上去。

**Comment by rmtic** [comment]
好，谢谢

**Comment by JingYeoh** [comment]
@rmtic 已经修复，请用v1.2.2版本

**Comment by rmtic** [comment]
内容区怎么取消手势滑动啊，我只想用按钮去控制它打开菜单

**Comment by JingYeoh** [comment]
@rmtic 我会在下个版本支持该操作～尽快完成～

**Comment by chendida** [comment]
大神，我菜单栏打开时，点击内容区域，这个时候内容区域的点击事件会响应，如何拦截，设置了app:contentToggle="true"无效啊

**Comment by JingYeoh** [comment]
@rmtic 请升级版本至`v1.3.0`并使用`allowDragging`属性或者`setAllowTogging`方法控制是否允许通过滑动控制菜单的关闭/打开。

**Comment by JingYeoh** [comment]
@chendida 请参照demo确认是否正确使用，我用demo中的onClick事件debug过了，在`app:contentToggle="true"`时点击事件会被拦截掉。
>如果不支持你需要的场景，请升级版本至`1.3.0`并使用`addOnSlideChangedListener`方法来监听菜单是否打开，然后设置你的内容区域是否允许点击。

**Comment by chendida** [comment]
好的，非常感谢

**Comment by rmtic** [comment]
大神，非常感谢你！
