### ISSUE TITLE
SlideMenuLayout 布局一定要3个子view吗

### ISSUE THREAD

**Issue by rmtic** [YangJing96/SlideMenuLayout#6]
<com.jkb.slidemenu.SlideMenuLayout
        android:id="@+id/mainSlideMenu"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        app:slideMode="both">
        <include layout="@layout/content_menu_left" />
        <include layout="@layout/content_menu_right" />
        <include layout="@layout/content_menu_content" />
 </com.jkb.slidemenu.SlideMenuLayout>

我只include left 和 content的时候，日志提示我要3个布局。

**Comment by JingYeoh** [comment]
@rmtic `app:slideMode="both"`你设置的滑动模式为`both`，只设置一个布局？那你此时的左右滑动怎么产生呢？
