### ISSUE TITLE
布局设置为none后无法打开菜单

### ISSUE THREAD

**Issue by rmtic** [YangJing96/SlideMenuLayout#7]
布局： app:slideMode="none"
需求: 
1. 设置 content 布局不可滑动
2. 点击“左上角”的菜单图标，滑动出left布局

问题：在开发的时候，布局设置成app:slideMode="none"的时候，使用slideMenu.toggleLeftSlide();
菜单没有滑动出来。能否增加个onToggleChangeListener的方法

**Comment by JingYeoh** [comment]
@rmtic none的含义是不使用侧滑菜单，不使用的意思是没有侧滑，没有侧滑如何滑出？
