### ISSUE TITLE
如何控制滑动关闭??设置none提示缺少布局，添加了布局还卡住界面，不能自动缩放

### ISSUE THREAD

**Issue by chenenqiang12345** [YangJing96/SlideMenuLayout#9]
如何控制滑动关闭??设置none提示缺少布局，添加了布局还卡住界面，不能自动缩放

**Comment by JingYeoh** [comment]
@chenenqiang12345 `none`是完全不使用侧滑菜单，但是近期很多人有只通过开关打开菜单而不使用滑动的需求，所以周末会加上该特性！

**Comment by JingYeoh** [comment]
@chenenqiang12345 请升级版本到`v1.3.0`并使用`allowDragging`属性控制是否关闭滑动。
